spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Bibliotopia
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

        format_sql: true
        default_batch_fetch_size: 10
  data:
    web:
      pageable:
        default-page-size: 3
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    session:
      persistent: false
      timeout: 30m
      tracking-modes: cookie

